name: Main Flow

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_KEY: ${{secrets.VITE_SUPABASE_KEY}}

    steps:
      - name: Check secrets
        if: ${{ env.VITE_SUPABASE_KEY == '' }}
        run: |
          echo 'Couldn't find the secret VITE_SUPABASE_KEY'
          exit 1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependecies
        run: bun i

      - name: Build app
        run: bun run build
