name: Main Flow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependecies
        run: bun i

      - name: Build app
        run: bun run build
